apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clicars-ingress
spec:
  rules:
    - host: tetris.127-0-0-1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tetris
                port:
                  number: 80
